"""Write README.md to project root."""
from pathlib import Path

ROOT = Path(__file__).parent.parent

content = (
    "# Prediccion de Riesgo Perinatal — DANE Nacimientos 2018\n\n"
    "Sistema de machine learning para predecir dos outcomes clinicos criticos\n"
    "a partir de los microdatos de nacimientos del DANE (Colombia, 2018):\n\n"
    "1. **Probabilidad de parto por cesarea**\n"
    "2. **Riesgo de bajo peso al nacer** (< 2 500 g)\n\n"
    "---\n\n"
    "## Arquitectura del Proyecto\n\n"
    "```\n"
    "proyecto-mlops/\n"
    "├── data/\n"
    "│   ├── raw/\n"
    "│   │   └── nac2018.csv              # Dataset original DANE (~649 000 registros)\n"
    "│   └── processed/\n"
    "│       └── nac2018_cleaned.csv      # Dataset limpio post-pipeline\n"
    "│\n"
    "├── notebooks/\n"
    "│   ├── 01_limpieza_datos.ipynb      # Limpieza y validacion de datos\n"
    "│   ├── 02_eda_processor.ipynb       # Analisis Exploratorio de Datos (EDA)\n"
    "│   └── 03_modelado_ml.ipynb         # Entrenamiento y evaluacion de modelos\n"
    "│\n"
    "├── src/\n"
    "│   ├── __init__.py\n"
    "│   ├── preprocessing.py             # Pipeline de limpieza y feature engineering\n"
    "│   └── train.py                     # Entrenamiento, evaluacion y persistencia de modelos\n"
    "│\n"
    "├── app/\n"
    "│   └── main.py                      # Interfaz grafica Streamlit\n"
    "│\n"
    "├── models/                          # Modelos entrenados (generados al ejecutar)\n"
    "│   ├── cesarea_pipeline.pkl\n"
    "│   └── bajo_peso_pipeline.pkl\n"
    "│\n"
    "├── scripts/\n"
    "│   └── generate_notebooks.py        # Generador de notebooks\n"
    "│\n"
    "├── main.py                          # CLI: pipeline completo + entrenamiento\n"
    "├── pyproject.toml                   # Configuracion del proyecto (UV)\n"
    "├── uv.lock                          # Lock file de dependencias\n"
    "└── diccionario_datos.md             # Diccionario de datos DANE\n"
    "```\n\n"
    "---\n\n"
    "## Flujo del Pipeline\n\n"
    "```\n"
    "nac2018.csv (crudo, 62 MB)\n"
    "      |\n"
    "      v\n"
    "[01_limpieza_datos.ipynb]\n"
    "  - Carga con encoding latin-1\n"
    "  - Reporte de valores faltantes\n"
    "  - Eliminacion de columnas irrelevantes (23 columnas)\n"
    "  - Imputacion de nulos administrativos con -1\n"
    "  - Correccion del encoding de PESO_NAC (codigos DANE 1-9, no gramos)\n"
    "  - Filtrado de registros invalidos\n"
    "  - Feature engineering: CESAREA, BAJO_PESO, EDAD_RIESGO, PREMATURO\n"
    "      |\n"
    "      v\n"
    "nac2018_cleaned.csv\n"
    "      |\n"
    "      v\n"
    "[02_eda_processor.ipynb]\n"
    "  - Distribucion de variables objetivo\n"
    "  - Analisis por edad materna, gestacion, acceso a salud\n"
    "  - Distribucion geografica por departamento\n"
    "  - Matriz de correlacion entre features y targets\n"
    "      |\n"
    "      v\n"
    "[03_modelado_ml.ipynb]\n"
    "  - Preparacion de 10 features\n"
    "  - Validacion cruzada estratificada (5 folds)\n"
    "  - Comparacion: Logistic Regression | Random Forest | HistGradientBoosting\n"
    "  - Curvas ROC y matrices de confusion\n"
    "  - Importancia de variables\n"
    "  - Persistencia de modelos en models/\n"
    "      |\n"
    "      v\n"
    "[app/main.py] — Streamlit\n"
    "  - Formulario de ingreso de datos clinicos\n"
    "  - Gauges de probabilidad para cesarea y bajo peso\n"
    "  - Identificacion de factores de riesgo\n"
    "  - Tabla de resumen clinico\n"
    "```\n\n"
    "---\n\n"
    "## Nota Critica: Codificacion de PESO_NAC\n\n"
    "El DANE codifica `PESO_NAC` como **categoria numerica** (no gramos):\n\n"
    "| Codigo | Rango de peso | Bajo peso |\n"
    "|--------|---------------|-----------|\n"
    "| 1 | < 1 000 g | Si |\n"
    "| 2 | 1 000 - 1 499 g | Si |\n"
    "| 3 | 1 500 - 1 999 g | Si |\n"
    "| 4 | 2 000 - 2 499 g | Si |\n"
    "| 5 | 2 500 - 2 999 g | No |\n"
    "| 6 | 3 000 - 3 499 g | No |\n"
    "| 7 | 3 500 - 3 999 g | No |\n"
    "| 8 | 4 000 - 4 499 g | No |\n"
    "| 9 | >= 4 500 g | No |\n\n"
    "`BAJO_PESO = 1` cuando `PESO_NAC in {1, 2, 3, 4}` (codigos < 2 500 g).\n\n"
    "El pipeline anterior usaba `between(400, 7000)` sobre estos codigos,\n"
    "lo que eliminaba **todos** los 649 115 registros. Este error esta corregido.\n\n"
    "---\n\n"
    "## Variables del Modelo\n\n"
    "### Features (10 variables de entrada)\n\n"
    "| Variable | Descripcion | Tipo |\n"
    "|----------|-------------|------|\n"
    "| EDAD_MADRE | Edad de la madre en anos | Numerica |\n"
    "| T_GES | Semanas de gestacion al nacer | Numerica |\n"
    "| NUMCONSUL | Consultas prenatales realizadas | Numerica |\n"
    "| N_HIJOSV | Numero de hijos vivos actualmente | Numerica |\n"
    "| N_EMB | Total de embarazos (incluye el actual) | Numerica |\n"
    "| AREA_RES | Area de residencia (1: urbana, 2: centro, 3: rural) | Categorica |\n"
    "| IDCLASADMI | Regimen de salud (1: contributivo, 2: subsidiado) | Categorica |\n"
    "| SEXO | Sexo del neonato (1: masculino, 2: femenino) | Categorica |\n"
    "| MUL_PARTO | Tipo de gestacion (1: unico, 2: gemelar, 3+: multiple) | Categorica |\n"
    "| CODPTORE | Codigo del departamento de residencia | Categorica |\n\n"
    "### Targets (variables objetivo)\n\n"
    "| Variable | Descripcion | Positivo |\n"
    "|----------|-------------|----------|\n"
    "| CESAREA | Parto por cesarea | TIPO_PARTO == 2 |\n"
    "| BAJO_PESO | Bajo peso al nacer | PESO_NAC in {1,2,3,4} |\n\n"
    "---\n\n"
    "## Modelos Evaluados\n\n"
    "| Modelo | Descripcion |\n"
    "|--------|-------------|\n"
    "| LogisticRegression | Baseline lineal, rapido e interpretable |\n"
    "| RandomForestClassifier | Ensemble de arboles, robusto a no-linearidades |\n"
    "| HistGradientBoostingClassifier | Boosting eficiente, mejor rendimiento en datos grandes |\n\n"
    "- **Metrica de seleccion:** ROC-AUC en 5-fold CV estratificado\n"
    "- **Manejo de desbalance:** `class_weight='balanced'` en todos los modelos\n"
    "- **Preprocesamiento:** SimpleImputer + StandardScaler para numericas;\n"
    "  SimpleImputer + OneHotEncoder para categoricas\n\n"
    "---\n\n"
    "## Requisitos\n\n"
    "- Python >= 3.12\n"
    "- [UV](https://docs.astral.sh/uv/) — gestor de entornos virtuales\n\n"
    "### Dependencias principales\n\n"
    "| Paquete | Version minima | Uso |\n"
    "|---------|---------------|-----|\n"
    "| pandas | 2.2.0 | Manipulacion de datos |\n"
    "| scikit-learn | 1.5.0 | Modelos ML y pipelines |\n"
    "| numpy | 1.26.0 | Calculo numerico |\n"
    "| matplotlib | 3.9.0 | Visualizaciones |\n"
    "| seaborn | 0.13.2 | Visualizaciones estadisticas |\n"
    "| plotly | 5.24.0 | Graficos interactivos |\n"
    "| streamlit | 1.40.0 | Interfaz grafica web |\n"
    "| joblib | 1.4.0 | Serializacion de modelos |\n\n"
    "---\n\n"
    "## Instalacion y Uso\n\n"
    "### 1. Instalar UV\n\n"
    "```bash\n"
    "# Windows (PowerShell)\n"
    "powershell -ExecutionPolicy ByPass -c \"irm https://astral.sh/uv/install.ps1 | iex\"\n\n"
    "# Linux / macOS\n"
    "curl -LsSf https://astral.sh/uv/install.sh | sh\n"
    "```\n\n"
    "### 2. Clonar y configurar\n\n"
    "```bash\n"
    "git clone https://github.com/jmarangom/ju-ca-nacimientos2018.git\n"
    "cd ju-ca-nacimientos2018\n"
    "uv sync\n"
    "```\n\n"
    "### 3. Colocar el dataset\n\n"
    "Descargue los microdatos desde el DANE y coloque el archivo en:\n\n"
    "```\n"
    "data/raw/nac2018.csv\n"
    "```\n\n"
    "URL: https://microdatos.dane.gov.co/index.php/catalog/652\n\n"
    "### 4. Opcion A — CLI (recomendado)\n\n"
    "```bash\n"
    "uv run python main.py\n"
    "```\n\n"
    "Ejecuta limpieza + feature engineering + entrenamiento de ambos modelos.\n\n"
    "### 5. Opcion B — Notebooks paso a paso\n\n"
    "```bash\n"
    "uv run jupyter notebook\n"
    "```\n\n"
    "Ejecutar en orden:\n"
    "1. `notebooks/01_limpieza_datos.ipynb`\n"
    "2. `notebooks/02_eda_processor.ipynb`\n"
    "3. `notebooks/03_modelado_ml.ipynb`\n\n"
    "### 6. Interfaz grafica\n\n"
    "```bash\n"
    "uv run streamlit run app/main.py\n"
    "```\n\n"
    "Abrir en el navegador: http://localhost:8501\n\n"
    "---\n\n"
    "## Fuentes y Referencias\n\n"
    "- **Dataset:** DANE — Estadisticas Vitales, Microdatos Nacimientos 2018\n"
    "  https://microdatos.dane.gov.co/index.php/catalog/652\n"
    "- **OMS — Bajo peso al nacer:** https://www.who.int/topics/low_birthweight\n\n"
    "---\n\n"
    "## Autores\n\n"
    "- Proyecto iniciado por jmarangom\n"
    "- Colaboracion: Carolina Uribe\n"
)

(ROOT / "README.md").write_text(content, encoding="utf-8")
print("README.md written successfully")
